language: node_js
node_js:
- stable
script: npx maid prepublish
env:
  - secure: "oqh4srT+DAStF9pV2z6txsArGF037LPpl6eXeV/j9MaX3tyihDgDwKCZyEieFfo4gSjoDwBcS6FU4WVSv1HS2YHHL6dDabOZp3mlpsz5hvJ3EbAziWMhnv79CUxwxr0VBqdCrXQSbQztlpUSprpn77zp1wYeMj9dsxexhjU0dcmRJNtdv4E7pM930zXvp+h2ZkzlS4+0VrvxbOVERo5fW7fozUVnyf+L3HbwEA7WUdk9QaZN7C3GxamFmgpkw9YtJbhCq5wH/OuWNe9HRAbNoeDnHMcm8eGAtitj9KyfVloequ/ZSJAAwzNsqkQkK2mTJJoXDAp0Z/VXZMOnEciqB7uKaYwYI1orgo42Jec5kBM5JzGrewcWb/FeI7v+Qk7UEwVinX8TG1d4yuuOA96E6GHn8lj0cyfKzeUaFzUk3a5mlZ6QqZRTma3S5/u3GRTgh2jd+6YlZpNXjqNfJoQj7wU5G8dZ8wdfOU+wjQawZgylUn6jSJLxn0KLozaSdyN46yuYADz5Yr2S/Fhk3INCIcpk51cRP2rnIYXngx7sAeSvcyjj7rjtP72PyQRDKllEENFW7rSgNvmwza2flBeyLiNQi+bm6F+nzuyaQRyPxnzfKPIEDT9YugT3ByTrB2BmQcBzfD0iHQGop362NRKPMfY6huWJ5bIUj9ldhxY95e8="
