language: node_js
node_js:
- stable
script: npx maid prepublish
env:
  - secure: "W4FURx33W06wLPNnJRFfNxqBo+JX7O50PuFz8PvRk2P8dfMP5zF9MjS9ybrcwXrSpDMXiKy1xYxucnbdquJ6VNOCx/tdsAX8VVbdZtC3eAe7MSQdQHXJCH+yHQR2p2rQUSJdXuwLunNlJiCTR6k89V6vfjLssJ0wa/X2r7Kty1jMX6UkH/d32TawiXV9pNgBD4CWvGE5FK3wLPy1nUpsyzVXg1NcqqeokXFc6b9bu72DYwBXpLgCGlaCjnZPSOme/jAHOzoENP9ywsNa+8YFyVll5vrhZE0ELyiOkrDDldJx0/AZW59zArlenu/9wheVZdIwxkjL2DKqX9m+JKrL8FguimvIYC4mVE2ikVNg7NAGalXv1ilQGcdsJ+GR7vhyJ9zIRgBPTuMzaRSI1bkF1Gm4bYgmtNvIZhiIbOVKYJ4JZUZysSkMrkHuX7SUr2DNpKTEa86rolJpEo4AcEAc4ART2DKC7cazHDl0qlcuzQhvoRAwVrmjDqDguQklOZVIRdKQRPBO/Q4ElOaRFwir5eocCk0RfD3tW/xKhT7HKVR+behxNcvM6J0B7WnF8R878w8uFvRYWFurMekBwK605c+7Bae4Mw8Qd6WCu9VnLkDYo4pk8yHyypRPK91YULkTP2YnfAXjIl5EEPljpkkmJ24pL2z/DnCIk/xTjzMnsYE="
